event/urls.py
from django.contrib import admin
from django.urls import path
from .import views

# set up urls for all pages in the event app
urlpatterns = [
    path('', views.index, name='index'),
    path('events', views.events, name='events'),
    path('event/<int:event_id>/', views.event_detail, name='event_detail'),
    path('create-event', views.create_event, name='create'),
    path('manage-events', views.manage_events, name='manage'),
    path('edit/<int:event_id>/', views.edit_event, name='edit_event'),
    path('delete/<int:event_id>/', views.delete_event, name='delete_event'),
]

subsurface/urls.py
from django.contrib import admin
from django.urls import path, include

# all urls in the project
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('event.urls')),
    path('newsletter/', include('newsletter.urls')),
    path('', include('contact.urls')),
    path('', include('tickets.urls')),
]
# add differrent error page urls for common errors
handler404 = 'subsurface.views.custom_404'
handler500 = 'subsurface.views.custom_500'
handler403 = 'subsurface.views.custom_403'
handler400 = 'subsurface.views.custom_400'

event/models.py
from django.db import models
from django.db import models
from django.utils import timezone
from cloudinary.models import CloudinaryField

# event Model


class Event(models.Model):
    event_id = models.AutoField(primary_key=True)
    event_name = models.CharField(max_length=200)
    genre = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    address = models.CharField(max_length=255)
    organiser = models.CharField(max_length=100)
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    event_description = models.TextField()
    artists = models.CharField(max_length=255)
    date_uploaded = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    music = models.URLField(max_length=200, blank=True, null=True)
    event_image = models.CharField(max_length=255, blank=True, null=True)
    featured = models.BooleanField(default=False)
    # extend event model with ticket price for each event
    ticket_price = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00)
    # extend event model with max tickets sold
    max_tickets = models.PositiveIntegerField(default=100)

    def __str__(self):
        return self.event_name

    # if the event date is today, return today instead of the date, same with 'tomorrow'

    @property
    def formatted_date(self):
        # get today's date in the correct timezone
        today = timezone.localdate()
        # get the event's date
        event_date = self.date

        # if the event is today, return "Today"
        if event_date == today:
            return "Today"
        # if the event is tomorrow, return "Tomorrow"
        elif event_date == today + timezone.timedelta(days=1):
            return "Tomorrow"
        # if the event is in the same week as today, return the day name
        elif event_date.isocalendar()[1] == today.isocalendar()[1]:
            return event_date.strftime('%A')
        # if the event is in the same year as today, return the month and day
        elif event_date.year == today.year:
            return event_date.strftime('%B %d')
        # if the event is in a different year, return the full date
        else:
            return event_date.strftime('%B %d, %Y')

    @property
    def remaining_tickets(self):
        # calculate remaining tickets
        tickets_bought = self.ticket_set.aggregate(
            total_quantity=models.Sum('quantity'))
        total_tickets_bought = tickets_bought['total_quantity'] or 0
        return self.max_tickets - total_tickets_bought

event/forms.py
from django import forms
from .models import Event


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = [
            'event_name', 'date', 'start_time', 'end_time', 'city', 'address',
            'genre', 'organiser', 'event_description', 'artists', 'music', 'event_image', 'featured', 'ticket_price', "max_tickets"
        ]

event/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import EventForm
from .models import Event
# import timezone to check if event is in the past
from django.utils import timezone
# import allauth decorator to check if admin is logged in, add it to all admin restricted views
from django.contrib.auth.decorators import user_passes_test
# import messages
from django.contrib import messages


# check if username is administrator
def is_administrator(user):
    """ A view to check if the user has admin rights """
    return user.is_authenticated and user.username == 'administrator'

# home page


def index(request):
    """ A view to return the index page with only featured events """
    featured_events = Event.objects.filter(featured=True)
    return render(request, 'event/index.html', {'events': featured_events})

# all events page


def events(request):
    """ A view to return the events page with filtering """
    # check if event is in the past, only return current or future ones
    events = Event.objects.filter(date__gte=timezone.now())

    # get filter parameters from the request
    genre = request.GET.get('event_type')
    date = request.GET.get('date')
    city = request.GET.get('event_city')

    # apply filters if parameters are provided
    if genre:
        events = events.filter(genre=genre)
    if date:
        events = events.filter(date=date)
    if city:
        events = events.filter(city=city)

    # render the template with the filtered events
    return render(request, 'event/events.html', {'events': events})

# create event page for the administrator


@user_passes_test(is_administrator)
def create_event(request):
    """ A view to return the create event page """
    if request.method == "POST":
        form = EventForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'New event uploaded successfully.')
            return redirect('manage')
        else:
            messages.error(request, 'There was an error uploading the event.')
    else:
        form = EventForm()
    return render(request, 'event/create_event.html', {'form': form})

# manage event page for the administrator


@user_passes_test(is_administrator)
def manage_events(request):
    """ A view to return the manage events page """
    events = Event.objects.all()
    return render(request, 'event/manage.html', {'events': events})

# edit each event page for the administrator


@user_passes_test(is_administrator)
def edit_event(request, event_id):
    """ A view to return the edit event page """
    event = get_object_or_404(Event, event_id=event_id)
    if request.method == 'POST':
        form = EventForm(request.POST, request.FILES, instance=event)
        if form.is_valid():
            form.save()
            messages.success(request, 'Event edited successfully.')
            return redirect('manage')
        else:
            messages.error(request, 'There was an error editing the event.')
    else:
        form = EventForm(instance=event)
    return render(request, 'event/edit_event.html', {'form': form, 'event': event})

# delete event page for the administrator with confirmation


@user_passes_test(is_administrator)
def delete_event(request, event_id):
    """ A view for deleting an event """
    event = get_object_or_404(Event, event_id=event_id)
    if request.method == 'POST':
        event.delete()
        messages.success(request, 'Event deleted successfully.')
        return redirect('manage')
    return render(request, 'event/delete_event.html', {'event': event})

# event detail page for each event


def event_detail(request, event_id):
    """ A view to return the event detail pages """
    event = get_object_or_404(Event, event_id=event_id)
    artist_list = event.artists.split(',')
    context = {
        'event': event,
        'artist_list': artist_list,
    }
    return render(request, 'event/event_detail.html', context)

event/templates/event/create_event.html
{% extends "base.html" %}
{% load static %}
<!-- Add title -->
{% block extra_title %} Create an event {% endblock %}

<!-- Extend base template with content -->
{% block content %}
<!-- Page Content -->
<div class="container mt-5 sexy-font">
    <h1>Upload Event</h1>
    <p class="text-muted">Fill out the form below to upload a new event.</p>
</div>

<!-- Upload Event Form -->
<div class="container mt-4">
    <form id="upload-event-form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- add featured checkbox -->
        <div class="form-check mb-4">
            <input class="form-check-input" type="checkbox" id="event-featured" name="featured" value="true">
            <label class="form-check-label" for="event-featured">
                Featured Event
            </label>
        </div>
        <div class="row">
            <div class="col-md-6 mb-3">
                <label for="event-name" class="form-label">Event Name *</label>
                <input type="text" class="form-control" id="event-name" name="event_name"
                    placeholder="Name of the event." required>
            </div>
            <div class="col-md-6 mb-3">
                <label for="event-date" class="form-label">Date *</label>
                <input type="date" class="form-control" id="event-date" name="date" placeholder="Select a date."
                    required>
            </div>
            <div class="col-md-6 mb-3">
                <label for="event-start-time" class="form-label">Start Time *</label>
                <input type="time" class="form-control" id="event-start-time" name="start_time"
                    placeholder="When the event starts?" required>
            </div>
            <div class="col-md-6 mb-3">
                <label for="event-end-time" class="form-label">End Time *</label>
                <input type="time" class="form-control" id="event-end-time" name="end_time"
                    placeholder="When the event ends?" required>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 mb-3">
                <label for="event-city" class="form-label">City *</label>
                <select class="form-select" id="event-city" name="city" required>
                    <option value="" disabled selected>Choose a city.</option>
                    <option value="london">London</option>
                    <option value="birmingham">Birmingham</option>
                    <option value="manchester">Manchester</option>
                    <option value="bristol">Bristol</option>
                    <option value="liverpool">Liverpool</option>
                    <option value="cardiff">Cardiff</option>
                </select>
            </div>
            <div class="col-md-6 mb-3">
                <label for="event-venue" class="form-label">Address *</label>
                <input type="text" class="form-control" id="event-address" name="address"
                    placeholder="For example: BS2 5RH, Bass street 45..." required>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 mb-3">
                <label for="event-genre" class="form-label">Genre *</label>
                <select class="form-select" id="event-genre" name="genre" required>
                    <option value="" disabled selected>Choose a genre.</option>
                    <option value="techno">Techno</option>
                    <option value="house">House</option>
                    <option value="experimental">Experimental</option>
                    <option value="noise">Noise</option>
                </select>
            </div>
            <div class="col-md-6 mb-3">
                <label for="event-organiser" class="form-label">Organiser/Venue *</label>
                <input type="text" class="form-control" id="event-organiser" name="organiser"
                    placeholder="Who is organising this event?" required>
            </div>
        </div>

        <div class="mb-3">
            <label for="event-description" class="form-label">Description *</label>
            <textarea class="form-control" id="event-description" name="event_description" rows="5" required
                placeholder="What's this event is about?"></textarea>
        </div>
        <div class="mb-3">
            <label for="event-artists" class="form-label">Artists *</label>
            <input type="text" class="form-control" id="event-artists" name="artists"
                placeholder="Enter artist names separated by a comma..." required>
        </div>
        <div class="mb-3">
            <label for="event-music" class="form-label">Music (URL)</label>
            <input type="url" class="form-control" id="event-music" name="music"
                placeholder="Use a soundcloud, youtube spotify etc. link." required>
        </div>

        <div class="mb-4">
            <input type="hidden" id="id_event_image" name="event_image" value="https://i.ibb.co/pK1GWtT/default.png">
            <button type="button" id="upload_widget" class="btn btn-outline-light btn-lg btn-block mt-3">Upload
                Image</button>
            <div class="form-text" id="uploadStatusText">
                Click the button to upload your event image. For best results, please ensure the image is sized at
                1024x1024 pixels.
            </div>
        </div>
        <div class="row">
            <h2>Ticket Info</h2>
            <div class="col-md-6 mb-3">
                <!-- making sure that no negative values allowed -->
                <label for="ticket-price" class="form-label">Ticket Price *</label>
                <input type="number" step="0.01" class="form-control" id="ticket-price" name="ticket_price"
                       placeholder="Price per ticket" required min="0" oninput="validateTicketPrice(this)">
            </div>

            <script>
                function validateTicketPrice(input) {
                    // ensure value is non-negative
                    if (input.value < 0) {
                        input.value = 0;
                    }
                }
            </script>
            <div class="col-md-6 mb-3">
                <!-- validation to make sure only positive whole numbers used -->
                <label for="max-tickets" class="form-label">Max Tickets *</label>
                <input type="number" class="form-control" id="max-tickets" name="max_tickets"
                       placeholder="Maximum number of tickets available" required min="1" step="1" oninput="validateMaxTickets(this)">
            </div>
            
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-outline-warning btn-lg btn-block mt-3">Upload Event</button>
            <a href="{% url 'manage' %}" class="btn btn-outline-danger btn-lg btn-block mt-3">Cancel</a>
        </div>

    </form>
</div>
{% endblock %}
{% block postloadjs %}
<script src="https://widget.cloudinary.com/v2.0/global/all.js" type="text/javascript"></script>
<script type="text/javascript">
    var myWidget = cloudinary.createUploadWidget({
        cloudName: 'dpcst40m2',
        uploadPreset: 'rzidcahe'
    }, (error, result) => {
        if (!error && result && result.event === "success") {
            console.log('Done! Here is the image info: ', result.info);
            document.getElementById('id_event_image').value = result.info.secure_url;
            document.getElementById('uploadStatusText').textContent = "Image uploaded successfully!";
        } else if (error) {
            console.error('Upload error: ', error);
            document.getElementById('uploadStatusText').textContent = "Image upload failed. Please try again.";
        }
    });

    document.getElementById("upload_widget").addEventListener("click", function () {
        myWidget.open();
    }, false);


    function validateTicketPrice(input) {
        // make sure that the value is non-negative
        if (input.value < 0) {
            input.value = 0;
        }
    }
    function validateMaxTickets(input) {
        // make sure that the value is a whole positive number
        if (input.value < 1) {
            input.value = 1;
        } else {
            input.value = Math.floor(input.value);
        }
    }
</script>

{% endblock %}

event/templates/event/delete_event.html
{% extends "base.html" %}
{% load static %}
{% block extra_title %} Delete Event {% endblock %}

{% block content %}
<div class="container mt-5 sexy-font">
    <h1>Delete Event</h1>
    <p class="text-muted">Are you sure you want to delete this event?</p>
    <h2 class="mt-5 mb-5">{{ event.event_name }}</h2>
    <!-- if user forgot to add image use default image -->
    {% if event.event_image and event.event_image != "None" %}
    <img src="{{ event.event_image }}" class="img-fluid mb-3" alt="Event Image">
    {% else %}
    <img src="{% static 'images/default.png' %}" class="img-fluid mb-3" alt="Default Event Image">
    {% endif %}
    <form method="post" class="mt-4">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'manage' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

event/templates/event/edit_event.html
{% extends "base.html" %}
{% load static %}
<!-- Add title -->
{% block extra_title %} Edit Event {% endblock %}

<!-- Extend base template with content -->
{% block content %}
<!-- Page Content -->
<div class="container mt-5 sexy-font">
    <h1>Edit Event</h1>
    <p class="text-muted">Update the form below to edit the event details.</p>
</div>

<!-- edit event form -->
<div class="container mt-4">
    <form id="edit-event-form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- add featured checkbox -->
        <div class="form-check mb-4">
            <input class="form-check-input" type="checkbox" id="event-featured" name="featured" value="true" {% if form.featured.value %}checked{% endif %}>
            <label class="form-check-label" for="event-featured">
                Featured Event
            </label>
        </div>
        <div class="row">
            <div class="col-md-6 mb-3">
                <label for="event-name" class="form-label">Event Name *</label>
                <input type="text" class="form-control" id="event-name" name="event_name"
                    placeholder="Name of the event." value="{{ form.event_name.value }}" required>
            </div>
            <div class="col-md-6 mb-3">
                <label for="event-date" class="form-label">Date *</label>
                <input type="date" class="form-control" id="event-date" name="date" value="{{ form.date.value|date:'Y-m-d' }}" required>
            </div>
            <div class="col-md-6 mb-3">
                <label for="event-start-time" class="form-label">Start Time *</label>
                <input type="time" class="form-control" id="event-start-time" name="start_time" value="{{ form.start_time.value|time:'H:i' }}" required>
            </div>
            <div class="col-md-6 mb-3">
                <label for="event-end-time" class="form-label">End Time *</label>
                <input type="time" class="form-control" id="event-end-time" name="end_time" value="{{ form.end_time.value|time:'H:i' }}" required>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 mb-3">
                <label for="event-city" class="form-label">City *</label>
                <select class="form-select" id="event-city" name="city" required>
                    <option value="" disabled>Choose a city.</option>
                    <option value="london" {% if form.city.value == "london" %}selected{% endif %}>London</option>
                    <option value="birmingham" {% if form.city.value == "birmingham" %}selected{% endif %}>Birmingham</option>
                    <option value="manchester" {% if form.city.value == "manchester" %}selected{% endif %}>Manchester</option>
                    <option value="bristol" {% if form.city.value == "bristol" %}selected{% endif %}>Bristol</option>
                    <option value="liverpool" {% if form.city.value == "liverpool" %}selected{% endif %}>Liverpool</option>
                    <option value="cardiff" {% if form.city.value == "cardiff" %}selected{% endif %}>Cardiff</option>
                </select>
            </div>
            <div class="col-md-6 mb-3">
                <label for="event-venue" class="form-label">Address *</label>
                <input type="text" class="form-control" id="event-address" name="address"
                    placeholder="For example: BS2 5RH, Bass street 45..." value="{{ form.address.value }}" required>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 mb-3">
                <label for="event-genre" class="form-label">Genre *</label>
                <select class="form-select" id="event-genre" name="genre" required>
                    <option value="" disabled>Choose a genre.</option>
                    <option value="techno" {% if form.genre.value == "techno" %}selected{% endif %}>Techno</option>
                    <option value="house" {% if form.genre.value == "house" %}selected{% endif %}>House</option>
                    <option value="experimental" {% if form.genre.value == "experimental" %}selected{% endif %}>Experimental</option>
                    <option value="noise" {% if form.genre.value == "noise" %}selected{% endif %}>Noise</option>
                </select>
            </div>
            <div class="col-md-6 mb-3">
                <label for="event-organiser" class="form-label">Organiser/Venue *</label>
                <input type="text" class="form-control" id="event-organiser" name="organiser"
                    placeholder="Who is organising this event?" value="{{ form.organiser.value }}" required>
            </div>
        </div>
        
        <div class="mb-3">
            <label for="event-description" class="form-label">Description *</label>
            <textarea class="form-control" id="event-description" name="event_description" rows="5" required
                placeholder="What's this event about?">{{ form.event_description.value }}</textarea>
        </div>
        <div class="mb-3">
            <label for="event-artists" class="form-label">Artists *</label>
            <input type="text" class="form-control" id="event-artists" name="artists"
                placeholder="Enter artist names separated by a comma..." value="{{ form.artists.value }}" required>
        </div>
        <div class="mb-3">
            <label for="event-music" class="form-label">Music (URL)</label>
            <input type="url" class="form-control" id="event-music" name="music"
                placeholder="Use a SoundCloud, YouTube, Spotify, etc. link." value="{{ form.music.value }}">
        </div>
        <div class="mb-3">
            <label for="id_event_image_url" class="form-label">Event Image URL</label>
            <input type="text" id="id_event_image" name="event_image" class="form-control" value="{{ form.event_image.value|default_if_none:event.event_image }}">
            <small class="form-text text-muted">You can only edit the URL for this image.</small>
        </div>
        <div class="row">
            <h2>Ticket Info</h2>
            <div class="col-md-6 mb-3">
                <label for="ticket-price" class="form-label">Ticket Price *</label>
                <input type="number" step="0.01" class="form-control" id="ticket-price" name="ticket_price"
                    placeholder="Price per ticket" value="{{ form.ticket_price.value }}" required>
            </div>
            <div class="col-md-6 mb-3">
                <label for="max-tickets" class="form-label">Max Tickets *</label>
                <input type="number" class="form-control" id="max-tickets" name="max_tickets"
                    placeholder="Maximum number of tickets available" value="{{ form.max_tickets.value }}" required>
            </div>
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-outline-warning btn-lg btn-block mt-3">Update Event</button>
            <a href="{% url 'manage' %}" class="btn btn-outline-danger btn-lg btn-block mt-3">Cancel</a>
        </div>
    </form>
</div>
{% endblock %}

event/templates/event/event_detail.html
<!-- templates/event_detail.html -->
{% extends 'base.html' %}
{% load static %}

{% block extra_title %}
{{ event.event_name }}
{% endblock %}

{% block content %}
<!-- Page Content -->
<div class="container mt-5 sexy-font">
    <h1>{{ event.event_name }}</h1>
    <h4 class="">{{ event.organiser }}, {{ event.city }} - {{ event.formatted_date }}</h4>
</div>

<!-- event image -->
<div class="container mt-4">
    <div class="row">
        <div class="col-12">
            <!-- if user forgot to add image use default image -->
            {% if event.event_image and event.event_image != "None" %}
                <img src="{{ event.event_image }}" class="img-fluid w-100" alt="Event Image">
            {% else %}
                <img src="{% static 'images/default.png' %}" class="img-fluid w-100" alt="Default Event Image">
            {% endif %}
        </div>
    </div>
</div>

<!-- event details -->
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8">
            <h2>Event Description</h2>
            <p class="text-wrap text-break p-3">{{ event.event_description }}</p>
            <p>Artists:</p>

            <ul>
                {% for artist in artist_list %}
                <li>{{ artist }}</li>
                {% endfor %}
            </ul>
            <p>Don't miss out on this unique event that pushes the boundaries of music and art. Get your tickets now and
                be part of an extraordinary night!</p>
            <a href="{{ event.music }}" target="_blank">Listen here</a>
        </div>
        <div class="col-md-4">
            <h2>Event Details</h2>
            <table class="table">
                <tr>
                    <th scope="row">Date</th>
                    <td>{{ event.date }}</td>
                </tr>
                <tr>
                    <th scope="row">Time</th>
                    <td>{{ event.start_time }} - {{ event.end_time }}</td>
                </tr>
                <tr>
                    <th scope="row">Venue</th>
                    <td>{{ event.organiser }}</td>
                </tr>
                <tr>
                    <th scope="row">Address</th>
                    <td>{{ event.address }}</td>
                </tr>
                <tr>
                    <th scope="row">City</th>
                    <td>{{ event.city }}</td>
                </tr>
                <tr>
                    <th scope="row">Genre</th>
                    <td>{{ event.genre }}</td>
                </tr>
                <tr>
                    <th scope="row">Ticket Price</th>
                    <td>£ {{ event.ticket_price }}</td>
                </tr>
            </table>

            <a href="{% url 'buy_ticket' event.event_id %}" class="btn btn-outline-warning btn-lg btn-block mt-3">
                <span class="bi bi-ticket-fill me-1"></span> Get Tickets
            </a>
        </div>
    </div>
</div>
{% endblock %}

event/templates/event/index.html
{% extends "base.html" %}
{% load static %}
<!-- Add title -->
{% block extra_title %} Home {% endblock %}

<!-- Extend base template with content -->
{% block content %}
<!-- Page Content -->
<div class="container mt-5 sexy-font">
    <h1>Discover the best underground music events.</h1>
</div>
<div class="container mt-5">
    <h2>Essential Gatherings:</h2>
    {% if events %}
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-3 g-5">
        {% for event in events %}
        <div class="col">
            <div class="position-relative square-container">
                <div class="date-overlay p-2">{{ event.date }}</div>
                <div class="city-overlay p-2">{{ event.city }}</div>
                <!-- if user forgot to add image use default image -->
                {% if event.event_image and event.event_image != "None" %}
                    <img src="{{ event.event_image }}" class="square-image" alt="Event Image">
                {% else %}
                    <img src="{% static 'images/default.png' %}" class="square-image" alt="Default Event Image">
                {% endif %}
                <div class="featured-badge">Featured</div>
            </div>
            <div class="card-body mt-2 text-center">
                <div class="d-flex align-items-center justify-content-center">
                    <!-- change the color depending on the genre -->
                    <p class="badge text-decoration-none mb-2
                        {% if event.genre == 'techno' %}bg-dark
                        {% elif event.genre == 'experimental' %}bg-warning
                        {% elif event.genre == 'noise' %}bg-danger
                        {% elif event.genre == 'house' %}bg-success
                        {% else %}bg-secondary{% endif %}">
                        {{ event.genre }}
                </p>
                    <p class="card-text mb-1">{{ event.organiser }}</p>
                </div>
                <h5 class="card-title">{{ event.event_name }}</h5>
                <a href="{% url 'buy_ticket' event.event_id %}" class="btn btn-warning btn-sm mt-2">
                    <span class="bi bi-ticket-fill me-1"></span> Get Tickets
                </a>
                <a href="{% url 'event_detail' event.event_id %}" class="btn btn-outline-warning btn-sm mt-2">
                    <span class="bi bi-calendar-event me-1"></span> Tell me more
                </a>
            </div>

        </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="container mt-5 text-center">
        <h2>No events at the moment. Come back later!</h2>
    </div>
    {% endif %}
</div>
{% endblock %}